name: Watchlist Service CD

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        continue-on-error: false
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: false
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cinerate-watchlist-service:latest
            ${{ secrets.DOCKER_USERNAME }}/cinerate-watchlist-service:v1.0.3
            ${{ secrets.DOCKER_USERNAME }}/cinerate-watchlist-service:${{ github.sha }}
        continue-on-error: false
